# FIle name: main.py
# external library: requirements.sh
# OS: ubuntu-latest

name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python Python/ETF/AAPL.py; python Python/ETF/GOOGL.py; python Python/ETF/MSFT.py; python Python/Cryptocurrency/BTC.py; Python/Cryptocurrency/ETH.py; Python/Cryptocurrency/SOL.py; Python/Index/ABCERI.py; Python/Index/BGCI.py; Python/Index/NDX.py; Python/Mutual Fund/AGTHX.py;
